### ISSUE TITLE
Publish rust-freetype on crates.io

### ISSUE THREAD

**Issue by staktrace** [servo/rust-freetype#42]
Right now @jrmuizel 's Gecko-WebRenderer branch has webrender building using a [direct git dependency](https://github.com/jrmuizel/gecko-dev/blob/d6d52f976d0688100366cad5eed3d9aea8ebff13/gfx/webrender/Cargo.toml#L30) on this library. As far as I can tell that doesn't work well with the mozilla-central way of importing rust libraries (i.e. the `mach vendor rust` process) because it can't pull the dependency into the third_party/ folder properly. It would be great if we could publish a version of this library to crates.io so that we can add the dependency that way.

**Comment by staktrace** [comment]
Based on the Cargo.toml file in this repo, the project is intended to published as "freetype" on crates.io, which is a placeholder owned by @SimonSapin, so presumably he's the one who can do this?

**Comment by SimonSapin** [comment]
My name shows up there because I originally registered the crate name, but `github:servo:cargo-publish` is also an "owner" so anyone in that github team (which is roughly the same set of people as the reviewers on servo repositories) can publish.

I just published what’s currently in master as version 0.1.1.

**Comment by staktrace** [comment]
Ah, good to know. And thank you!
